account/urls.py
from django.urls import path
from django.conf.urls import url
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [

    # Account Home
    path('', views.account_index, name='index'),

    # Profile Index
    path('profile/<uuid:uuid>/', views.profile_index, name='profile-index'),

    # Profile Detail
    path('profile/<uuid:uuid>/detail/', views.profile_detail, name='profile-detail'),

    # Profile Edit
    path('profile/<uuid:uuid>/edit/', views.profile_edit, name='profile-edit'),

    # Profile Entries
    path('profile/<uuid:uuid>/entries/<int:type>/',
        views.profile_entries, name='profile-entries'),


    ## THIS PAGE IS WHERE THEY SET THEIR PROFILE AND ROSTER CARD IMAGE
    path('profile/<uuid:uuid>/image/', views.profile_image, name='profile-image'),


    ## THIS IS GOING TO BE PROFILE GALLERY IMAGES
    ## change this to a different name

    # ProfileImage List
    path('profile/<uuid:uuid>/images/',
        views.profileimage_list, name='profileimage-list'),

    # ProfileImage Detail
    path('profile/<uuid:uuid>/images/<int:id>/',
        views.profileimage_detail, name='profileimage-detail'),

    # ProfileImage Detail
    path('profile/<uuid:uuid>/images/<int:id>/edit/',
        views.profileimage_edit, name='profileimage-edit'),

    # ProfileImage New
    path('profile/<uuid:uuid>/images/new/',
        views.profileimage_new, name='profileimage-new'),

    # ProfileImage Delete
    path('profile/<uuid:uuid>/images/<int:id>/delete/',
        views.profileimage_delete, name='profileimage-delete'),

    # ProfileImage Set as Profile Image
    path('profile/<uuid:uuid>/images/<int:id>/profile/',
        views.profileimage_profile_image, name='profileimage-profile-image'),

    # ProfileImage Set as Roster Image
    path('profile/<uuid:uuid>/images/<int:id>/roster/',
        views.profileimage_roster_image, name='profileimage-roster-image'),

    # an How To and Profile Example
    path('profile/<uuid:uuid>/example/', views.profile_example, name='profile-example'),

    # Old Highlights
    path('profile/<uuid:uuid>/past/', views.oldhighlights, name='oldhighlights'),

    # Delete Old Highlight
    path('profile/<uuid:uuid>/oldhighlight/<int:id>/delete/',
        views.oldhighlight_delete, name='oldhighlight-delete'),

    # Profile Entry Detail
    path('profile/<uuid:uuid>/entry/<int:id>/',
        views.entry_detail, name='entry-detail'),

    # Profile Entry Delete
    path('profile/<uuid:uuid>/entry/<int:id>/delete/',
        views.entry_delete, name='entry-delete'),

    # Profile Dates
    path('profile/<uuid:uuid>/dates/',
        views.profile_dates, name='profile-dates'),

    # Delete TeamDate
    path('profile/<uuid:uuid>/teamdate/<int:id>/delete/',
        views.teamdate_delete, name='teamdate-delete'),

    # Delete ArmyDate
    path('profile/<uuid:uuid>/armydate/<int:id>/delete/',
        views.armydate_delete, name='armydate-delete'),

    # ProfileStory List
    path('profile/<uuid:uuid>/stories/',
        views.profilestory_list, name='profilestory-list'),

    # ProfileStory Detail
    path('profile/<uuid:uuid>/story/<int:id>/',
        views.profilestory_detail, name='profilestory-detail'),

    # ProfileStory New
    path('profile/<uuid:uuid>/story/new/',
        views.profilestory_new, name='profilestory-new'),

    # ProfileStory Edit
    path('profile/<uuid:uuid>/story/<int:id>/edit/',
        views.profilestory_edit, name='profilestory-edit'),

    # ProfileStory Delete
    path('profile/<uuid:uuid>/story/<int:id>/delete/',
        views.profilestory_delete, name='profilestory-delete'),


    # Profile Public Comment
    path('profile/<uuid:uuid>/comments/',
        views.profile_comments, name='profile-comments'),

    # Profile Current Status
    path('profile/<uuid:uuid>/status/',
        views.profile_current_status, name='profile-current-status'),

    # Account Request
    path('new/request/', views.accountrequest_new, name='accountrequest-new'),

    path('new/request/<uuid:uuid>/',
        views.accountrequest_confirmed, name='accountrequest-confirmed'),


    ## LOGIN | AUTH INFO | LOGIN | AUTH INFO
    ## LOGIN | AUTH INFO | LOGIN | AUTH INFO

    # login info
    path('login/', auth_views.LoginView.as_view(
        redirect_authenticated_user=True), name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # password reset
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
        success_url='/account/password-reset/done/'),
        name="password-reset"
        ),

    # url after you submit your email address
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),

    # url that confirms the link you clicked in your email
    path('password-reset/confirm/<str:uidb64>/<str:token>/',
        auth_views.PasswordResetConfirmView.as_view(
            success_url='/account/password-reset/complete/'),
            name = "password-reset-confirm"
        ),

    # url that confirms you are done and offers link to login
    path('password-reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password-reset-complete'
        ),

    # sandbox
    path('sandbox/', views.sandbox, name='sandbox'),
    path('sandbox/user/connect/', views.sandbox_connect_user, name='sandbox-connect-user'),
    path('sandbox/originaluser/type/', views.sandbox_originaluser_type, name='originaluser-type'),


]

app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [

    path('', views.app_index, name='app-index'),

    path('accountrequests/', views.accountrequest_list, name='accountrequest-list'),

    path('accountrequest/<int:pk>/',
        views.accountrequest_detail, name='accountrequest-detail'),

    path('accountrequest/<int:pk>/delete/',
        views.accountrequest_delete, name='accountrequest-delete'),

    path('accountrequest/<int:pk>/set-pending/',
        views.accountrequest_set_pending, name='accountrequest-set-pending'),

    path('accountrequest/<int:pk>/set-later/',
        views.accountrequest_set_later, name='accountrequest-set-later'),

    path('accountrequest/<int:pk>/complete/',
        views.accountrequest_complete, name='accountrequest-complete'),

    path('armydate/<int:pk>/delete/', views.armydate_delete, name='armydate-delete'),

    path('user/new/<int:pk>/', views.customuser_new, name='customuser-new'),

    path('user/<int:pk>/', views.customuser_detail, name='customuser-detail'),

    path('users/', views.customuser_list, name='customuser-list'),

    path('dues/', views.duespayment_list, name='duespayment-list'),

    # Events
    path('events/', views.event_list, name='event-list'),
    path('events/<int:pk>/', views.event_detail, name='event-detail'),
    path('events/<int:pk>/email/', views.event_email, name='event-email'),

    path('events/<int:pk>/registration/',
        views.eventregistration_new, name='eventregistration-new'),

    path('registration/<int:pk>/',
        views.eventregistration_detail, name='eventregistration-detail'),

    # Gallery
    path('gallery/', views.gallery_list, name='gallery-list'),
    path('gallery/<int:pk>/', views.gallery_detail, name='gallery-detail'),
    path('galleryimage/<int:pk>/', views.galleryimage_detail, name='galleryimage-detail'),

    path('search/', views.app_search, name='search'),

    path('profile/<int:pk>/', views.profile_detail, name='profile-detail'),

    path('profile/<int:pk>/edit/', views.profile_edit_view, name='profile-edit'),

    path('profile/<int:pk>/dates/', views.profile_dates, name='profile-dates'),

    path('profile/<int:pk>/entries/<int:type>/',
        views.profile_entries, name='profile-entries'),

    path('profile/new/', views.profile_new, name='profile-new'),

    path('profile/<int:pk>/split/',
        views.profile_split_entry_view, name='profile-split-entry'),

    path('profile/<int:pk>/set-user/<int:id>/',
        views.profile_set_user, name='profile-set-user'),

    # ProfileUpdate List
    path('profileupdates/',
        views.profileupdate_list, name='profileupdate-list'),

    # ProfileImage List
    path('profile/<int:pk>/images/',
        views.profileimage_list, name='profileimage-list'),

    # ProfileImage New
    path('profile/<int:pk>/images/new/',
        views.profileimage_new, name='profileimage-new'),

    # ProfileImage Detail
    path('profile/<int:pk>/images/<int:id>/',
        views.profileimage_detail, name='profileimage-detail'),

    # ProfileImage Edit
    path('profile/<int:pk>/images/<int:id>/edit/',
        views.profileimage_edit, name='profileimage-edit'),

    # ProfileImage Delete
    path('profile/<int:pk>/images/<int:id>/delete/',
        views.profileimage_delete, name='profileimage-delete'),

    # ProfileImage Set as Profile Image
    path('profile/<int:pk>/images/<int:id>/profile/',
        views.profileimage_profile_image, name='profileimage-profile-image'),

    # ProfileImage Set as Profile Image
    path('profile/<int:pk>/images/<int:id>/roster/',
        views.profileimage_roster_image, name='profileimage-roster-image'),


    path('teamdate/<int:pk>/delete/', views.teamdate_delete, name='teamdate-delete'),

    path('entry/<int:pk>/', views.entry_detail, name='entry-detail'),

    path('entry/<int:pk>/delete/', views.entry_delete, name='entry-delete'),

    path('subevents/<int:pk>/', views.subevent_detail, name='subevent-detail'),

    # Emails
    path('user/<int:pk>/send-account-email/',
        views.send_user_account_email, name='send-user-account-email'),

    # ProfileStory List
    path('profile/<int:pk>/stories/',
        views.profilestory_list, name='profilestory-list'),

     # ProfileStory New
    path('profile/<int:pk>/stories/new/',
        views.profilestory_new, name='profilestory-new'),

    # ProfileStory Detail
    path('profile/<int:pk>/stories/<int:id>/',
        views.profilestory_detail, name='profilestory-detail'),

    # ProfileStory Edit
    path('profile/<int:pk>/stories/<int:id>/edit/',
        views.profilestory_edit, name='profilestory-edit'),

    # ProfileStory Delete
    path('profile/<int:pk>/stories/<int:id>/delete/',
        views.profilestory_delete, name='profilestory-delete'),


    # TEMPORARY VIEWS # TEMPORARY VIEWS
    # ProfileStory Delete
    path('temp/', views.temp_index, name='temp-index'),


    ### Clean Up Below Here

    # Profile Update Priority List
    path('profiles/priority/', views.profile_priority_list, name='profile-priority'),

    # Go To Profile
    path('profiles/<int:pk>/go/', views.profile_go_action, name='profile-go'),

    # sandbox
    path('sandbox/', views.sandbox, name='sandbox'),
    path('sandbox/registration/name/', views.sandbox_registration_name, name='registration-name'),
    path('sandbox/searchfield/', views.sandbox_search_field, name='sandbox-searchfield'),
    path('sandbox/stripnames/', views.sandbox_strip_names, name='sandbox-stripnames'),
    path('sandbox/highlight/sortorder/', views.sandbox_highlight_sort_order, name='sandbox-sortorder'),
    path('sandbox/gallery/transfer/', views.sandbox_gallery_transfer, name='sandbox-gallery-transfer'),
    path('sandbox/galleryimage/exists/', views.sandbox_galleryimage_exists, name='sandbox-galleryimage-exists'),
]

gkaa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('app/', include('app.urls')),

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

website/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'website'
urlpatterns = [

    # index pages

    path('robots.txt', TemplateView.as_view(template_name='website/robots.txt', content_type="text/plain"), name="robots"),

    path('', views.index, name='index'),

    path('contact/', views.contact_us_view, name='contact'),

    # Event Detail (Event Description)
    path('event/<str:event_code>/', views.event_detail, name='event-detail'),

    # Event Detail Register View
    path('event/<str:event_code>/register/', views.event_register, name='event-register'),

    # Create the New Event Registration (AJAX)
    path('event/registration/new/', views.event_register_new),

    # Event Payment View Page
    path('event/registration/<str:short_code>/payment/',
        views.event_registration_payment, name='eventregistration-payment'),

    # Event Charge Action
    path('event/registration/<str:short_code>/charge/',
        views.event_registration_charge, name='eventregistration-charge'),

    # Event Complete (no balance due)
    path('event/registration/<str:short_code>/complete/',
        views.event_registration_complete, name='eventregistration-complete'),

    # Registration Detail
    path('event/registration/<str:short_code>/',
        views.event_registration_detail, name='eventregistration-detail'),

    # gallery
    path('gallery/', views.gallery_index, name='gallery-index'),
    path('gallery/<slug:slug>/', views.gallery_detail, name='gallery-detail'),
    path('gallery/<slug:slug>/<uuid:uuid>/', views.galleryimage_detail, name='galleryimage-detail'),


    path('history/', views.history_view, name='history'),

    path('roster/', views.roster_list, name='roster'),
    path('roster/menu/', views.roster_menu, name='roster-menu'),

    # Profile
    path('profile/<str:url_code>/', views.profile_view, name='profile'),
    path('profile/<str:url_code>/ext/', views.extended_profile_view, name='extended-profile'),


    # Pay Dues
    path('pay-dues/', views.pay_dues_view, name='pay-dues'),
    path('pay-dues/<uuid:uuid>/', views.pay_dues_charge_view, name='pay-dues-charge'),
    path('pay-dues/<uuid:uuid>/confirm/', views.pay_dues_confirm_view, name='pay-dues-confirm'),

    # Stripe
    path('api/stripe/charge/new/', views.stripe_charge_new, name='stripe-charge-new'),

    # Global Charge Success Page
    path('<str:type>/<uuid:id>/success/', views.charge_success_view, name='charge-success'),

    # Validate Email
    path('api/validate/email/', views.validate_email_action, name='validate-email'),


    # Donations
    path('donate/', views.donate_view, name='donate'),

    path('sandbox/', views.sandbox, name='sandbox'),


    # Non Login, Event Check In
    path('checkin/<slug:slug>/',
        views.checkin_event_detail, name='checkin-event-detail'),

    path('checkin/<slug:slug>/<int:pk>/',
        views.checkin_subevent_detail, name='checkin-subevent-detail'),

    path('registration/<int:pk>/',
        views.checkin_subeventregistration_detail, name='checkin-subeventregistration-detail'),

    path('registration/<int:pk>/checkin/',
        views.checkin_subeventregistration_checkin, name='checkin-subeventregistration-checkin'),






]

website/views/actions.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import Q
from django.conf import settings
from django.http import JsonResponse

from django.core.exceptions import ValidationError
from django.core.validators import validate_email

from random import randrange, shuffle
from decimal import Decimal
import json
import datetime

import stripe

from app.models import AccountRequest, Event, EventRegistration
from utils.utils import create_short_code
from utils.stripe import create_stripe_charge, stripe_charge_registration, stripe_charge_dues, stripe_charge_donation


# Charge Stripe Account
def stripe_charge_new(request):

    if request.is_ajax():

        token = request.POST['token_id'].strip()
        payment_type = request.POST['payment_type'].strip()
        payment_type_id = request.POST['payment_type_id'].strip()
        payment_amount = request.POST['payment_amount'].strip()
        payment_email = request.POST['payment_email'].strip()

        # to use this for more than one charge type, I will need to create a util
        # campaigns, dues, etc
        if payment_type == 'event':

            return_obj = stripe_charge_registration(
                payment_type_id = payment_type_id,
                token = token
                )

        elif payment_type == 'dues':

            return_obj = stripe_charge_dues(
                type_id = payment_type_id,
                token = token,
                amount = int(payment_amount),
                email = payment_email
            )


        elif payment_type == 'donation':

            payment_name = request.POST['payment_name'].strip()
            payment_note = request.POST['payment_note'].strip()

            return_obj = stripe_charge_donation(
                token = token,
                amount = int(payment_amount),
                name = payment_name,
                email = payment_email,
                note = payment_note
            )


        return JsonResponse(return_obj)

    else:
        return HttpResponse('is POST')

def validate_email_action(request):

    if request.is_ajax():

        email = request.POST['email'].strip()

        try:
            validate_email(email)
            email_is_valid = 'true'
        except:
            email_is_valid = ''

        return_obj = {
            'is_valid': email_is_valid
        }


        return JsonResponse(return_obj)

    else:
        return HttpResponse('')

website/templates/website/event_registration_detail.html
{% extends "websitebase.html" %}
{% load static %}

{% block content %}
<div class="container mb-3" style="margin-top:25px;max-width:400px;">
  <div class="row">

    <div class="col-12 text-md">


        {% if total %}

        <h3 class="fw-bold text-center">
          Paid!
        </h3>

        <p class="text-center">
          Check your email for a receipt.
        </p>

        {% else %}

        <h2 class="fw-bold text-center mb-0">
          You are Registered!
        </h2>

        <p class="my-0 text-center">
          See details below.
        </p>

        {% endif %}<!-- end if no total (free w/ dues) -->

        <hr/>

        <p>
          As promised, this party is 100% free!
        </p>

        <p>
          Because the GKAA is a non-profit organization, annual dues and
          donations are always needed.
        </p>

        <p>
          If you are an <strong>Alumnus</strong> and have not paid your annual dues...
        </p>

        <p>
          ...or an Alumnus, Honorary GK, current team member or
          friend of the team and would like to make a donation,
          you can do so using one of the following links.
        </p>

        <div class="d-grid mb-3">
          <a class="btn btn-gold btn-lg"
            href="{% url 'website:pay-dues'%}">
            Pay Annual Dues
          </a>
        </div>

        <div class="d-grid">
          <a class="btn btn-dark btn-lg"
            href="{% url 'website:donate'%}">
            Make a 501(c)(19) Donation
          </a>
        </div>


        <hr>

        <p class="my-0">
          <strong>Event:</strong> {{ registration.event.name }}
        </p>

        {% if subevent_list %}
        <ul class="my-0">
          {% for sub in subevent_list %}
            <li>
              {{ sub.name }} ({{ sub.quantity }})
            </li>
          {% endfor %}

          {% if registration.dues_added %}
            <li>Annual Dues ($50)</li>
          {% endif %}

        </ul>
        {% endif %}

        <p class="my-0">
          <strong>Name:</strong> {{ registration.name }}
        </p>

        <p class="my-0">
          <strong>Email:</strong> {{ registration.email_display }}
        </p>

        <p class="my-0">
          <strong>Date:</strong> {{ registration.date }}
        </p>

        {% if registration.add_dues %}
        <p class="my-0">
          <strong>2020 Dues:</strong> $50
        </p>
        {% endif %}

        <p class="my-0">
          <strong>Payment Total:</strong> ${{ total }}
        </p>

    </div>

    <!-- TEMP-->
    <div style="margin:15px;"></div>

  </div>
</div>
{% endblock %}

website/templates/website/gallery_detail.html
{% extends "websitebase.html" %}

{% block content %}
<div class="hero-gallery">
  <div class="container">
    <div class="row">
      <div class="col-12">

        <h1 class="mb-0">
          US ARMY
          <span class="d-block d-md-none"></span>
          GOLDEN KNIGHTS
        </h1>

        <h2 class="my-0">
          {{ gallery.name }}
        </h2>

      </div>
    </div>
  </div>
</div>

<div class="bg-black">
  <div class="container py-3">
    <div class="row gx-0">
      {% for image in image_list %}
      <div class="col-6 col-md-4 col-lg-3 p-2">
        <a href="{% url 'website:galleryimage-detail' image.slug image.uuid %}">
          <img class="img-fluid" src="{{ image.src }}">
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

website/templates/website/galleryimage_detail.html
{% extends "websitebase.html" %}

{% block content %}
<div class="container mt-4" style="max-width:768px;">

  <div class="row">
    <div class="col-12">

      <a class="h5 me-3" href="{% url 'website:gallery-index' %}">
        &laquo; Gallery Home
      </a>

      <a class="h5" href="{% url 'website:gallery-detail' gallery.slug %}">
        &laquo; {{ gallery.name }}
      </a>

    </div>
  </div>

  <div class="row">

    <div class="col-12">
      <img class="img-fluid mx-auto d-block mt-3" src="{{ image.detail_src }}">
    </div>

  </div>
</div>

<div class="container" style="max-width:668px">
  <div class="row">
    <div class="col-12">

      <p class="pt-3 text-center my-0" style="font-size:1.4rem;">
        {{ image.caption }}

        {% if image.year %}
          <br>
          <strong><em>Year: </em></strong>{{ image.year }}
        {% endif %}

        {% if image.credit %}
          <br>
          <strong><em>Credit: </em></strong>{{ image.credit }}
        {% endif %}

      </p>

    </div>
  </div>
</div>

<div class="bg-black mt-5">
  <div class="container gallery py-5">
    <div class="row gx-0">
      {% for image in image_list %}
      <div class="col-6 col-md-4 col-lg-3 p-2">
        <a href="{% url 'website:galleryimage-detail' image.slug image.uuid %}">
          <img class="img-fluid" src="{{ image.src }}">
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/pay_dues.html
{% extends "websitebase.html" %}
{% load static %}

{% block content %}
<div class="container mb-3" style="margin-top:50px;max-width:450px;">
  <div class="row">
    <div class="col-12">

      <h1 class="fw-bold">
        Pay Your {{ year }} Dues
      </h1>

      <hr/>

      <p>
        Annual Dues are $50. To pay your dues, enter at least the
        first three characters of your
        <strong>Last Name</strong> in the
        search block below.
      </p>

      <p>
        Then click the blue Pay Dues button next to your name.
      </p>

      <form class="" action="{% url 'website:pay-dues' %}" method="post">
        {% csrf_token %}

        <div class="mb-3">
          <input class="form-control" type="text" name="dues_search"
            placeholder="Enter Your Last Name">
        </div>

        <div class="d-grid">
          <button type="submit" class="btn btn-gold btn-lg btn-block">
            Search Member Database
          </button>
        </div>

      </form>
    </div>

    <div class="col-12">

      <ul class="list-group mt-3">
        {% for profile in dues_search %}
          <li class="list-group-item d-flex justify-content-between align-items-center">

            <a href="{% url 'website:pay-dues-confirm' profile.uuid %}">
              {{ profile }} ({{ profile.start_year }})
            </a>

            <a class="btn btn-sm btn-primary"
              href="{% url 'website:pay-dues-confirm' profile.uuid %}">
              Pay Dues
            </a>

          </li>
        {% endfor %}
      </ul>

    </div>

  </div>
</div>
{% endblock %}

website/templates/website/profile.html
{% extends "websitebase.html" %}

{% block content %}
<div class="bg-white py-4">
  <div class="container profile-container">

    <!--- navigation row -->
    <div class="row mb-2">
      <div class="col-6">

        {% if search %}
        <p class="my-0">
          <a href="{% url 'website:roster' %}?q={{ search }}">
            <i class="fas fa-angle-double-left"></i>
            Back to Roster
          </a>
        </p>
        {% else %}
        <p class="my-0">
          <a href="{% url 'website:roster' %}">
            <i class="fas fa-angle-double-left"></i>
            Back to Roster
          </a>
        </p>
        {% endif %}

      </div>

      <div class="col-6">
        <p class="text-end my-0">
          {% if show_edit_link %}
          <a href="{% url 'account:profile-detail' profile.uuid %}">
            Edit Your Profile
            <i class="fas fa-angle-double-right"></i>
          </a>
          {% endif %}
        </p>

      </div>
    </div><!--- end navigation row --->

    <div class="row">

      {% if profile.profile_image_src %}
      <div class="col-sm-6">

        <img class="img-fluid d-block mx-auto mt-sm-3 mb-3 mb-sm-0"
          src="{{ profile.profile_image_src }}"
          alt="{{ profile.first_name }} {{ profile.last_name }}">

      </div>
      {% endif %}

      <div class="col-sm-6">

        <h1 class="fw-bold">
          {{profile.first_name }} {{ profile.last_name }}
        </h1>

        {% if profile.nickname %}
          <p class="my-1"><strong>Nickname:</strong> {{ profile.nickname }}</p>
        {% endif %}

        {% if profile.aka %}
          <p class="my-1"><strong>AKA:</strong> {{ profile.aka }}</p>
        {% endif %}

        {% if profile.rank %}
          <p class="my-1"><strong>Rank on team:</strong> {{ profile.rank }}</p>
        {% endif %}

        {% if profile.show_home_origin %}
          <p class="my-1">
            <strong>Hometown:</strong>
            {{ profile.show_home_origin }}
          </p>
        {% endif %}

        {% if profile.show_deceased_date %}
          <p class="my-1"><strong>Deceased: </strong>{{ profile.show_deceased_date }}</p>
        {% endif %}

        {% if profile.teamdate_string %}
        <p class="my-1">
          <strong>Assigned:</strong>
          {{ profile.teamdate_string }}
        </p>
        {% endif %}

        <!--- home highlights and extended profile -->
        <ul style="padding-left:1rem;">

          {% if profile.home_highlights %}

            {% for highlight in profile.home_highlights %}
              <li class="my-2">{{ highlight }}</li>
            {% endfor %}

          {% endif %}<!-- endif home highlights -->

          {% if profile.extended_profile %}
           <li>
             <a
               href="{% url 'website:extended-profile' profile.url_code %}">
               Read more about {{ profile.first_name }} &raquo;
             </a>
           </li>
         {% endif %}

        </ul>

        {% if profile_comments %}
          <h4 class="fw-bold">Comments</h4>
          <p>
            {{ profile_comments }}

              {% if extended_comments %}
                <a href="{% url 'website:extended-profile' profile.url_code %}">
                  ...read more
                </a>
              {% endif %}
          </p>
        {% endif %}

      </div><!--- end info column --->
    </div>

  </div><!--- end container --->
</div><!--- end bg white--->

<div class="border-bottom bg-white">
  {% if profileimage_list %}
  <!-- IF after the top div so we still get the bottom border -->
  <div class="container pb-4">
    <div class="row">

      {% if show_more_images %}
      <div class="col-12">
        <p class="text-end">
          <a href="{% url 'website:extended-profile' profile.url_code %}">
            See More Pictures of {{ profile.first_name }}
            <i class="fas fa-angle-double-right"></i>
          </a>
        </p>
      </div>
      {% endif %}

      {% for image in profileimage_list %}
      <div class="col-6 col-md-3">
        <img class="img-fluid" src="{{ image.profile_src }}">
      </div>
      {% endfor %}
    </div>

  </div>
  {% endif %}
</div>


<!-- more GKs container -->
{% if more_knights %}
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h4 class="fw-bold">
        Know any of these GKs?
      </h4>
      <hr/>
    </div>
  </div>
  <div class="row">
    {% for knight in more_knights %}
    <div class="col-6 col-sm-4 col-lg-3">
      <p>
        <a href="{% url 'website:profile' knight.url_code %}">
          {{ knight.last_name }}, {{ knight.first_name }} <br/>
          {{ knight.start_year }}-{{ knight.end_year }}
        </a>
      </p>
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}<!-- endif more_knights -->

{% endblock %}