account/urls.py
from django.urls import path
from django.conf.urls import url
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [

    # Account Home
    path('', views.account_index, name='index'),

    # Profile Index
    path('profile/<uuid:uuid>/', views.profile_index, name='profile-index'),

    # Profile Detail
    path('profile/<uuid:uuid>/detail/', views.profile_detail, name='profile-detail'),

    # Profile Edit
    path('profile/<uuid:uuid>/edit/', views.profile_edit, name='profile-edit'),

    # Profile Entries
    path('profile/<uuid:uuid>/entries/<int:type>/',
        views.profile_entries, name='profile-entries'),


    ## THIS PAGE IS WHERE THEY SET THEIR PROFILE AND ROSTER CARD IMAGE
    path('profile/<uuid:uuid>/image/', views.profile_image, name='profile-image'),


    ## THIS IS GOING TO BE PROFILE GALLERY IMAGES
    ## change this to a different name

    # ProfileImage List
    path('profile/<uuid:uuid>/images/',
        views.profileimage_list, name='profileimage-list'),

    # ProfileImage Detail
    path('profile/<uuid:uuid>/images/<int:id>/',
        views.profileimage_detail, name='profileimage-detail'),

    # ProfileImage Detail
    path('profile/<uuid:uuid>/images/<int:id>/edit/',
        views.profileimage_edit, name='profileimage-edit'),

    # ProfileImage New
    path('profile/<uuid:uuid>/images/new/',
        views.profileimage_new, name='profileimage-new'),

    # ProfileImage Delete
    path('profile/<uuid:uuid>/images/<int:id>/delete/',
        views.profileimage_delete, name='profileimage-delete'),

    # ProfileImage Set as Profile Image
    path('profile/<uuid:uuid>/images/<int:id>/profile/',
        views.profileimage_profile_image, name='profileimage-profile-image'),

    # ProfileImage Set as Roster Image
    path('profile/<uuid:uuid>/images/<int:id>/roster/',
        views.profileimage_roster_image, name='profileimage-roster-image'),

    # an How To and Profile Example
    path('profile/<uuid:uuid>/example/', views.profile_example, name='profile-example'),

    # Old Highlights
    path('profile/<uuid:uuid>/past/', views.oldhighlights, name='oldhighlights'),

    # Delete Old Highlight
    path('profile/<uuid:uuid>/oldhighlight/<int:id>/delete/',
        views.oldhighlight_delete, name='oldhighlight-delete'),

    # Profile Entry Detail
    path('profile/<uuid:uuid>/entry/<int:id>/',
        views.entry_detail, name='entry-detail'),

    # Profile Entry Delete
    path('profile/<uuid:uuid>/entry/<int:id>/delete/',
        views.entry_delete, name='entry-delete'),

    # Profile Dates
    path('profile/<uuid:uuid>/dates/',
        views.profile_dates, name='profile-dates'),

    # Delete TeamDate
    path('profile/<uuid:uuid>/teamdate/<int:id>/delete/',
        views.teamdate_delete, name='teamdate-delete'),

    # Delete ArmyDate
    path('profile/<uuid:uuid>/armydate/<int:id>/delete/',
        views.armydate_delete, name='armydate-delete'),

    # ProfileStory List
    path('profile/<uuid:uuid>/stories/',
        views.profilestory_list, name='profilestory-list'),

    # ProfileStory Detail
    path('profile/<uuid:uuid>/story/<int:id>/',
        views.profilestory_detail, name='profilestory-detail'),

    # ProfileStory New
    path('profile/<uuid:uuid>/story/new/',
        views.profilestory_new, name='profilestory-new'),

    # ProfileStory Edit
    path('profile/<uuid:uuid>/story/<int:id>/edit/',
        views.profilestory_edit, name='profilestory-edit'),

    # ProfileStory Delete
    path('profile/<uuid:uuid>/story/<int:id>/delete/',
        views.profilestory_delete, name='profilestory-delete'),


    # Profile Public Comment
    path('profile/<uuid:uuid>/comments/',
        views.profile_comments, name='profile-comments'),

    # Profile Current Status
    path('profile/<uuid:uuid>/status/',
        views.profile_current_status, name='profile-current-status'),

    # Account Request
    path('new/request/', views.accountrequest_new, name='accountrequest-new'),

    path('new/request/<uuid:uuid>/',
        views.accountrequest_confirmed, name='accountrequest-confirmed'),


    ## LOGIN | AUTH INFO | LOGIN | AUTH INFO
    ## LOGIN | AUTH INFO | LOGIN | AUTH INFO

    # login info
    path('login/', auth_views.LoginView.as_view(
        redirect_authenticated_user=True), name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # password reset
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
        success_url='/account/password-reset/done/'),
        name="password-reset"
        ),

    # url after you submit your email address
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),

    # url that confirms the link you clicked in your email
    path('password-reset/confirm/<str:uidb64>/<str:token>/',
        auth_views.PasswordResetConfirmView.as_view(
            success_url='/account/password-reset/complete/'),
            name = "password-reset-confirm"
        ),

    # url that confirms you are done and offers link to login
    path('password-reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password-reset-complete'
        ),

    # sandbox
    path('sandbox/', views.sandbox, name='sandbox'),
    path('sandbox/user/connect/', views.sandbox_connect_user, name='sandbox-connect-user'),
    path('sandbox/originaluser/type/', views.sandbox_originaluser_type, name='originaluser-type'),


]

app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [

    path('', views.app_index, name='app-index'),

    path('accountrequests/', views.accountrequest_list, name='accountrequest-list'),

    path('accountrequest/<int:pk>/',
        views.accountrequest_detail, name='accountrequest-detail'),

    path('accountrequest/<int:pk>/delete/',
        views.accountrequest_delete, name='accountrequest-delete'),

    path('accountrequest/<int:pk>/set-pending/',
        views.accountrequest_set_pending, name='accountrequest-set-pending'),

    path('accountrequest/<int:pk>/set-later/',
        views.accountrequest_set_later, name='accountrequest-set-later'),

    path('accountrequest/<int:pk>/complete/',
        views.accountrequest_complete, name='accountrequest-complete'),

    path('armydate/<int:pk>/delete/', views.armydate_delete, name='armydate-delete'),

    path('user/new/<int:pk>/', views.customuser_new, name='customuser-new'),

    path('user/<int:pk>/', views.customuser_detail, name='customuser-detail'),

    path('users/', views.customuser_list, name='customuser-list'),

    path('dues/', views.duespayment_list, name='duespayment-list'),

    # Events
    path('events/', views.event_list, name='event-list'),
    path('events/<int:pk>/', views.event_detail, name='event-detail'),
    path('events/<int:pk>/email/', views.event_email, name='event-email'),

    path('events/<int:pk>/registration/',
        views.eventregistration_new, name='eventregistration-new'),

    path('registration/<int:pk>/',
        views.eventregistration_detail, name='eventregistration-detail'),

    # Gallery
    path('gallery/', views.gallery_list, name='gallery-list'),
    path('gallery/<int:pk>/', views.gallery_detail, name='gallery-detail'),
    path('galleryimage/<int:pk>/', views.galleryimage_detail, name='galleryimage-detail'),

    path('search/', views.app_search, name='search'),

    path('profile/<int:pk>/', views.profile_detail, name='profile-detail'),

    path('profile/<int:pk>/edit/', views.profile_edit_view, name='profile-edit'),

    path('profile/<int:pk>/dates/', views.profile_dates, name='profile-dates'),

    path('profile/<int:pk>/entries/<int:type>/',
        views.profile_entries, name='profile-entries'),

    path('profile/new/', views.profile_new, name='profile-new'),

    path('profile/<int:pk>/split/',
        views.profile_split_entry_view, name='profile-split-entry'),

    path('profile/<int:pk>/set-user/<int:id>/',
        views.profile_set_user, name='profile-set-user'),

    # ProfileUpdate List
    path('profileupdates/',
        views.profileupdate_list, name='profileupdate-list'),

    # ProfileImage List
    path('profile/<int:pk>/images/',
        views.profileimage_list, name='profileimage-list'),

    # ProfileImage New
    path('profile/<int:pk>/images/new/',
        views.profileimage_new, name='profileimage-new'),

    # ProfileImage Detail
    path('profile/<int:pk>/images/<int:id>/',
        views.profileimage_detail, name='profileimage-detail'),

    # ProfileImage Edit
    path('profile/<int:pk>/images/<int:id>/edit/',
        views.profileimage_edit, name='profileimage-edit'),

    # ProfileImage Delete
    path('profile/<int:pk>/images/<int:id>/delete/',
        views.profileimage_delete, name='profileimage-delete'),

    # ProfileImage Set as Profile Image
    path('profile/<int:pk>/images/<int:id>/profile/',
        views.profileimage_profile_image, name='profileimage-profile-image'),

    # ProfileImage Set as Profile Image
    path('profile/<int:pk>/images/<int:id>/roster/',
        views.profileimage_roster_image, name='profileimage-roster-image'),


    path('teamdate/<int:pk>/delete/', views.teamdate_delete, name='teamdate-delete'),

    path('entry/<int:pk>/', views.entry_detail, name='entry-detail'),

    path('entry/<int:pk>/delete/', views.entry_delete, name='entry-delete'),

    path('subevents/<int:pk>/', views.subevent_detail, name='subevent-detail'),

    # Emails
    path('user/<int:pk>/send-account-email/',
        views.send_user_account_email, name='send-user-account-email'),

    # ProfileStory List
    path('profile/<int:pk>/stories/',
        views.profilestory_list, name='profilestory-list'),

     # ProfileStory New
    path('profile/<int:pk>/stories/new/',
        views.profilestory_new, name='profilestory-new'),

    # ProfileStory Detail
    path('profile/<int:pk>/stories/<int:id>/',
        views.profilestory_detail, name='profilestory-detail'),

    # ProfileStory Edit
    path('profile/<int:pk>/stories/<int:id>/edit/',
        views.profilestory_edit, name='profilestory-edit'),

    # ProfileStory Delete
    path('profile/<int:pk>/stories/<int:id>/delete/',
        views.profilestory_delete, name='profilestory-delete'),


    # TEMPORARY VIEWS # TEMPORARY VIEWS
    # ProfileStory Delete
    path('temp/', views.temp_index, name='temp-index'),


    ### Clean Up Below Here

    # Profile Update Priority List
    path('profiles/priority/', views.profile_priority_list, name='profile-priority'),

    # Go To Profile
    path('profiles/<int:pk>/go/', views.profile_go_action, name='profile-go'),

    # sandbox
    path('sandbox/', views.sandbox, name='sandbox'),
    path('sandbox/registration/name/', views.sandbox_registration_name, name='registration-name'),
    path('sandbox/searchfield/', views.sandbox_search_field, name='sandbox-searchfield'),
    path('sandbox/stripnames/', views.sandbox_strip_names, name='sandbox-stripnames'),
    path('sandbox/highlight/sortorder/', views.sandbox_highlight_sort_order, name='sandbox-sortorder'),
    path('sandbox/gallery/transfer/', views.sandbox_gallery_transfer, name='sandbox-gallery-transfer'),
    path('sandbox/galleryimage/exists/', views.sandbox_galleryimage_exists, name='sandbox-galleryimage-exists'),
]

gkaa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('app/', include('app.urls')),

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

website/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'website'
urlpatterns = [

    # index pages

    path('robots.txt', TemplateView.as_view(template_name='website/robots.txt', content_type="text/plain"), name="robots"),

    path('', views.index, name='index'),

    path('contact/', views.contact_us_view, name='contact'),

    # Event Detail (Event Description)
    path('event/<str:event_code>/', views.event_detail, name='event-detail'),

    # Event Detail Register View
    path('event/<str:event_code>/register/', views.event_register, name='event-register'),

    # Create the New Event Registration (AJAX)
    path('event/registration/new/', views.event_register_new),

    # Event Payment View Page
    path('event/registration/<str:short_code>/payment/',
        views.event_registration_payment, name='eventregistration-payment'),

    # Event Charge Action
    path('event/registration/<str:short_code>/charge/',
        views.event_registration_charge, name='eventregistration-charge'),

    # Event Complete (no balance due)
    path('event/registration/<str:short_code>/complete/',
        views.event_registration_complete, name='eventregistration-complete'),

    # Registration Detail
    path('event/registration/<str:short_code>/',
        views.event_registration_detail, name='eventregistration-detail'),

    # gallery
    path('gallery/', views.gallery_index, name='gallery-index'),
    path('gallery/<slug:slug>/', views.gallery_detail, name='gallery-detail'),
    path('gallery/<slug:slug>/<uuid:uuid>/', views.galleryimage_detail, name='galleryimage-detail'),


    path('history/', views.history_view, name='history'),

    path('roster/', views.roster_list, name='roster'),
    path('roster/menu/', views.roster_menu, name='roster-menu'),

    # Profile
    path('profile/<str:url_code>/', views.profile_view, name='profile'),
    path('profile/<str:url_code>/ext/', views.extended_profile_view, name='extended-profile'),


    # Pay Dues
    path('pay-dues/', views.pay_dues_view, name='pay-dues'),
    path('pay-dues/<uuid:uuid>/', views.pay_dues_charge_view, name='pay-dues-charge'),
    path('pay-dues/<uuid:uuid>/confirm/', views.pay_dues_confirm_view, name='pay-dues-confirm'),

    # Stripe
    path('api/stripe/charge/new/', views.stripe_charge_new, name='stripe-charge-new'),

    # Global Charge Success Page
    path('<str:type>/<uuid:id>/success/', views.charge_success_view, name='charge-success'),

    # Validate Email
    path('api/validate/email/', views.validate_email_action, name='validate-email'),


    # Donations
    path('donate/', views.donate_view, name='donate'),

    path('sandbox/', views.sandbox, name='sandbox'),


    # Non Login, Event Check In
    path('checkin/<slug:slug>/',
        views.checkin_event_detail, name='checkin-event-detail'),

    path('checkin/<slug:slug>/<int:pk>/',
        views.checkin_subevent_detail, name='checkin-subevent-detail'),

    path('registration/<int:pk>/',
        views.checkin_subeventregistration_detail, name='checkin-subeventregistration-detail'),

    path('registration/<int:pk>/checkin/',
        views.checkin_subeventregistration_checkin, name='checkin-subeventregistration-checkin'),






]

templates/accountbase.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet"  href="{% static 'account/css/account.css' %}">
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">

    {% if load_trix %}
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/trix.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/trix_custom.css' %}">
    {% endif %}

    <title>GKAA Account</title>
  </head>
  <body>

    <div class="main-content pt-3">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <script async src="{% static 'account/js/account.js' %}" type="text/javascript"></script>

    {% if load_trix %}
    <script src="{% static '/account/js/trix.js' %}"></script>
    <script src="{% static '/account/js/trix_custom.js' %}"></script>
    {% endif %}

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/appbase.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet"  href="{% static 'app/css/app.css' %}">
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">

    {% if load_trix %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/trix.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/trix_custom.css' %}">
    {% endif %}

    <title>GKAA App</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'app:app-index' %}">GKAA Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Accounts
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <a class="dropdown-item" href="{% url 'app:accountrequest-list' %}">
                    Requests
                  </a>
                </li>
                <li>
                  <a class="dropdown-item"
                    href="{% url 'app:accountrequest-list' %}?s=pending">
                    Vetting
                  </a>
                </li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <a class="dropdown-item" href="{% url 'app:customuser-list' %}">
                    User List
                  </a>
                </li>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Profiles
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <a class="dropdown-item" href="">
                    Profile List
                  </a>
                </li>
                <li>
                  <a class="dropdown-item"
                    href="{% url 'app:profileupdate-list' %}">
                    Recent Updates
                  </a>
                </li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <a class="dropdown-item" href="{% url 'app:profile-new' %}">
                    + Profile
                  </a>
                </li>
              </ul>
            </li>

            <li class="nav-item">
              <a class="nav-link"
                href="{% url 'app:event-list' %}">
                Events
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link"
                href="{% url 'app:duespayment-list' %}">
                Dues
              </a>
            </li>

          </ul>
        </div>
      </div>
    </nav>

    <div class="content pt-3 mb-5">
        {% block content %}{% endblock %}
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <script src="{% static '/app/js/app.js' %}"></script>

    {% if load_trix %}
    <script src="{% static '/app/js/trix.js' %}"></script>
    <script src="{% static '/app/js/trix_custom.js' %}"></script>
    {% endif %}


  </body>
</html>

templates/base.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!--Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,700" rel="stylesheet">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">

    {% block stylesheets %}{% endblock %}

    <title>US Army Golden Knights Alumni Association</title>
  </head>

  <body class="d-flex flex-column h-100">

    <header>
      <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-black text-light">

        <a class="navbar-brand" href="{% url 'website:index' %}">
          <img class="img-fluid" src="{% static 'website/images/image_header.jpg' %}">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:roster' %}">

                <span class="d-none d-sm-block d-lg-none">Roster</span>
                <span class="d-block d-sm-none d-lg-block">GKAA Roster</span>

              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:contact' %}">

                <span class="d-none d-sm-block d-lg-none">Contact</span>
                <span class="d-block d-sm-none d-lg-block">Contact Us</span>

              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:pay-dues' %}">

                <span class="d-none d-sm-block d-lg-none">Dues</span>
                <span class="d-block d-sm-none d-lg-block">Pay Dues</span>

              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:donate' %}">Donate</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}">Login</a>
            </li>

          </ul>
        </div>

      </nav>
    </header>

    <main role="main" class="content">
      {% block content %}{% endblock %}
    </main>


    <footer class="footer bg-black mt-auto py-4">
      <div class="container">
        <span class="text-muted">© 2020 | Golden Knights Alumni Association</span>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <!--close navbar if we click outside it-->
    <script type="text/javascript">
      $(document).click(function(e) {
        if (!$(e.target).is('a')) {
          $('.collapse').collapse('hide');
        }
      });
    </script>

    {% block pagejs %}{% endblock %}


  </body>
</html>