app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [

    path('', views.app_index, name='app-index'),

    path('accountrequests/', views.accountrequest_list, name='accountrequest-list'),

    path('accountrequest/<int:pk>/',
        views.accountrequest_detail, name='accountrequest-detail'),

    path('accountrequest/<int:pk>/delete/',
        views.accountrequest_delete, name='accountrequest-delete'),

    path('accountrequest/<int:pk>/set-pending/',
        views.accountrequest_set_pending, name='accountrequest-set-pending'),

    path('accountrequest/<int:pk>/set-later/',
        views.accountrequest_set_later, name='accountrequest-set-later'),

    path('accountrequest/<int:pk>/complete/',
        views.accountrequest_complete, name='accountrequest-complete'),

    path('armydate/<int:pk>/delete/', views.armydate_delete, name='armydate-delete'),

    path('user/new/<int:pk>/', views.customuser_new, name='customuser-new'),

    path('user/<int:pk>/', views.customuser_detail, name='customuser-detail'),

    path('users/', views.customuser_list, name='customuser-list'),

    path('dues/', views.duespayment_list, name='duespayment-list'),

    # Events
    path('events/', views.event_list, name='event-list'),
    path('events/<int:pk>/', views.event_detail, name='event-detail'),
    path('events/<int:pk>/email/', views.event_email, name='event-email'),

    path('events/<int:pk>/registration/',
        views.eventregistration_new, name='eventregistration-new'),

    path('registration/<int:pk>/',
        views.eventregistration_detail, name='eventregistration-detail'),

    # Gallery
    path('gallery/', views.gallery_list, name='gallery-list'),
    path('gallery/<int:pk>/', views.gallery_detail, name='gallery-detail'),
    path('galleryimage/<int:pk>/', views.galleryimage_detail, name='galleryimage-detail'),

    path('search/', views.app_search, name='search'),

    path('profile/<int:pk>/', views.profile_detail, name='profile-detail'),

    path('profile/<int:pk>/edit/', views.profile_edit_view, name='profile-edit'),

    path('profile/<int:pk>/dates/', views.profile_dates, name='profile-dates'),

    path('profile/<int:pk>/entries/<int:type>/',
        views.profile_entries, name='profile-entries'),

    path('profile/new/', views.profile_new, name='profile-new'),

    path('profile/<int:pk>/split/',
        views.profile_split_entry_view, name='profile-split-entry'),

    path('profile/<int:pk>/set-user/<int:id>/',
        views.profile_set_user, name='profile-set-user'),

    # ProfileUpdate List
    path('profileupdates/',
        views.profileupdate_list, name='profileupdate-list'),

    # ProfileImage List
    path('profile/<int:pk>/images/',
        views.profileimage_list, name='profileimage-list'),

    # ProfileImage New
    path('profile/<int:pk>/images/new/',
        views.profileimage_new, name='profileimage-new'),

    # ProfileImage Detail
    path('profile/<int:pk>/images/<int:id>/',
        views.profileimage_detail, name='profileimage-detail'),

    # ProfileImage Edit
    path('profile/<int:pk>/images/<int:id>/edit/',
        views.profileimage_edit, name='profileimage-edit'),

    # ProfileImage Delete
    path('profile/<int:pk>/images/<int:id>/delete/',
        views.profileimage_delete, name='profileimage-delete'),

    # ProfileImage Set as Profile Image
    path('profile/<int:pk>/images/<int:id>/profile/',
        views.profileimage_profile_image, name='profileimage-profile-image'),

    # ProfileImage Set as Profile Image
    path('profile/<int:pk>/images/<int:id>/roster/',
        views.profileimage_roster_image, name='profileimage-roster-image'),


    path('teamdate/<int:pk>/delete/', views.teamdate_delete, name='teamdate-delete'),

    path('entry/<int:pk>/', views.entry_detail, name='entry-detail'),

    path('entry/<int:pk>/delete/', views.entry_delete, name='entry-delete'),

    path('subevents/<int:pk>/', views.subevent_detail, name='subevent-detail'),

    # Emails
    path('user/<int:pk>/send-account-email/',
        views.send_user_account_email, name='send-user-account-email'),

    # ProfileStory List
    path('profile/<int:pk>/stories/',
        views.profilestory_list, name='profilestory-list'),

     # ProfileStory New
    path('profile/<int:pk>/stories/new/',
        views.profilestory_new, name='profilestory-new'),

    # ProfileStory Detail
    path('profile/<int:pk>/stories/<int:id>/',
        views.profilestory_detail, name='profilestory-detail'),

    # ProfileStory Edit
    path('profile/<int:pk>/stories/<int:id>/edit/',
        views.profilestory_edit, name='profilestory-edit'),

    # ProfileStory Delete
    path('profile/<int:pk>/stories/<int:id>/delete/',
        views.profilestory_delete, name='profilestory-delete'),


    # TEMPORARY VIEWS # TEMPORARY VIEWS
    # ProfileStory Delete
    path('temp/', views.temp_index, name='temp-index'),


    ### Clean Up Below Here

    # Profile Update Priority List
    path('profiles/priority/', views.profile_priority_list, name='profile-priority'),

    # Go To Profile
    path('profiles/<int:pk>/go/', views.profile_go_action, name='profile-go'),

    # sandbox
    path('sandbox/', views.sandbox, name='sandbox'),
    path('sandbox/registration/name/', views.sandbox_registration_name, name='registration-name'),
    path('sandbox/searchfield/', views.sandbox_search_field, name='sandbox-searchfield'),
    path('sandbox/stripnames/', views.sandbox_strip_names, name='sandbox-stripnames'),
    path('sandbox/highlight/sortorder/', views.sandbox_highlight_sort_order, name='sandbox-sortorder'),
    path('sandbox/gallery/transfer/', views.sandbox_gallery_transfer, name='sandbox-gallery-transfer'),
    path('sandbox/galleryimage/exists/', views.sandbox_galleryimage_exists, name='sandbox-galleryimage-exists'),
]

gkaa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('app/', include('app.urls')),

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

app/models.py
from django.db import models
from django.db.models import Sum, Q
import uuid
import datetime

from decimal import Decimal

from users.models import CustomUser

class Profile(models.Model):
    member_id = models.PositiveIntegerField(default=0)
    rank = models.CharField(max_length=5,blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, blank=True)
    nickname = models.CharField(max_length=50,blank=True)
    aka = models.CharField(max_length=50,blank=True,verbose_name='AKA')
    hometown = models.CharField(max_length=100, blank=True)
    home_city = models.CharField(max_length=50, blank=True)
    home_state = models.CharField(max_length=2, blank=True)
    mos = models.CharField(max_length=3, blank=True)
    old_id = models.PositiveSmallIntegerField(default=0)
    alumnus_choice = 1
    current_choice = 2
    honorary_choice = 3
    strac_team = 4
    other_choice = 5
    type_choices = (
        (alumnus_choice, 'Alumnus/Alumnae'),
        (current_choice, 'Current Team Member'),
        (honorary_choice, 'Honorary GK'),
        (other_choice, 'Other')
    )
    type = models.IntegerField(choices=type_choices, default=alumnus_choice)
    team_highlights_old = models.TextField(blank=True)
    army_highlights_old = models.TextField(blank=True)
    civilian_highlights_old = models.TextField(blank=True)
    current_status = models.TextField(blank=True)
    current_status_old = models.TextField(blank=True)
    comments = models.TextField(blank=True)
    deceased_date = models.DateField(blank=True, null=True)
    deceased_year = models.PositiveIntegerField(blank=True, null=True)
    army_start_date = models.PositiveIntegerField(default=0,blank=True, null=True)
    army_end_date = models.PositiveIntegerField(default=0, blank=True, null=True)
    gkas_year = models.CharField(max_length=4, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    uuid = models.UUIDField(default=uuid.uuid4,editable=False)
    short_code = models.CharField(max_length=12)
    skip_state = models.BooleanField(default=False)
    admin_cleaned = models.BooleanField(default=False)
    do_not_display = models.BooleanField(default=False)
    search_field = models.TextField(blank=True)
    temp_user_id = models.PositiveIntegerField(default=0)
    has_thumbnail = models.BooleanField(default=False)
    thumbnail_checked = models.BooleanField(default=False)
    d_number = models.CharField(max_length=10, blank=True)
    old_highlights = models.BooleanField(default=False)
    url_code = models.CharField(max_length=15)
    update_priority = models.PositiveIntegerField(default=0)
    update_complete = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)
    teamdate_string = models.CharField(max_length=150,blank=True)
    show_link = models.BooleanField(default=False)

    def dues_paid(self):

        # set the current year
        current_year = int(datetime.datetime.now().year)

        dues_search = self.duespayment_set.filter(
                amount__gt=0,
                year__gte = current_year
            )

        if dues_search:
            are_dues_paid = True
        else:
            are_dues_paid = False

        return are_dues_paid

    def show_home_origin(self):

        if self.home_city and self.home_state:
            return self.home_city + ', ' + self.home_state
        elif not self.home_city and self.home_state:
            return self.home_state
        else:
            return None

    def show_deceased_date(self):

        if self.deceased_date:
            return self.deceased_date
        elif self.deceased_year:
            return self.deceased_year
        else:
            return None

    def start_year(self):

        if self.teamdate_set.count():
            start_year = self.teamdate_set.first().start_year
        else:
            start_year = None

        return start_year

    def end_year(self):

        if self.teamdate_set.count():

            if self.teamdate_set.first().end_year:
                end_year = self.teamdate_set.first().end_year
            else:
                end_year = None
        else:
            end_year = None

        return end_year

    # show the Extended Profile page?
    def extended_profile(self):

        if self.profileentry_set.count() > 2:
            extended = True
        else:
            extended = False

        return extended

    # show (3 highlights on Main Profile Page)
    def home_highlights(self):

        return self.profileentry_set.filter(
            show_on_home = True,
            date_delete__isnull = True,

        )[:3]

    # does the Profile have a Profile Image set up?
    def profile_image_src(self):

        image = self.profileimage_set.filter(profile_image=True).first()

        if image:

            imgix = (
                'https://gkaa.imgix.net/images/profiles/' + image.name +
                '?fit=fill&fill=solid&fill-color=ffffff&w=600&h=600'
            )

        elif self.has_thumbnail and self.thumbnail_checked:

            imgix = (
                'https://gkaa.imgix.net/images/roster/' +
                str(self.member_id) + '-detail-hero.jpg'
            )


        else:

            imgix = 'https://gkaa.imgix.net/images/assets/roster-owls-head-sm.jpg?fit=crop&w=300&h=300'

        return imgix

    def roster_image_src(self):

        roster_image = self.profileimage_set.filter(roster_image=True).first()
        profile_image = self.profileimage_set.filter(profile_image=True).first()

        if roster_image:
            image = roster_image
        elif profile_image:
            image = profile_image
        else:
            image = None

        # if there is an image, use it
        if image:

            imgix = (
                'https://gkaa.imgix.net/images/profiles/' + image.name +
                '?fit=fill&fill=solid&fill-color=ffffff&w=200&h=260'
            )

        # are we still using the old image (member_id)
        elif self.has_thumbnail and self.thumbnail_checked:

            imgix = (
                'https://gkaa.imgix.net/images/roster/' +
                str(self.member_id) + '-detail-hero.jpg' +
                '?fit=crop&w=200&h=260'
            )

        # if no other image, use the Owl's head
        else:

            imgix = 'https://gkaa.imgix.net/images/assets/roster-owls-head-sm.jpg?fit=crop&w=200&h=260'

        return imgix

    def note_list(self):
        return self.profileentry_set.filter(
            type=8,
            date_delete__isnull = True
            )

    def story_list(self):
        return self.profilestory_set.all()

    def oldhighlight_list(self):
        return self.oldhighlight_set.filter(
            date_delete__isnull=True
        )

    def oldhighlights(self):

        return self.oldhighlight_set.filter(
            date_delete__isnull = True
        )

    def image_list(self):
        return self.profileimage_set.filter(
            date_delete__isnull=True
        )

    def entry_list(self):

        # get all EntryTypes except Highlights & Admin Notes
        type_set = EntryType.objects.exclude(
            Q(slug = 'admin-notes')|
            Q(slug = 'entries')|
            Q(slug = 'links')|
            Q(slug = 'stories')|
            Q(slug = 'highlights')
        )

        the_list = []

        for type in type_set:

            entries = self.profileentry_set.filter(
                entrytype = type
            )

            type_obj = {
                'id': type.id,
                'title': type.title,
                'singular': type.singular,
                'entries': entries,
                'count': entries.count()
            }

            the_list.append(type_obj)

        return the_list

    def __str__(self):
        return self.last_name + str(', ') + self.first_name

class ProfileUpdate(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    action = models.CharField(max_length=250)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return str(self.profile)

class ProfileFilter(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField()
    active = models.BooleanField(default=False)
    use_filter_date = models.BooleanField(default=False)
    roster_card_title = models.CharField(max_length=20,blank=True)

    def __str__(self):
        return self.name

class ProfileFilterHolder(models.Model):
    profilefilter = models.ForeignKey(ProfileFilter,on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    sort_order = models.PositiveIntegerField(default=0)
    year = models.PositiveIntegerField(default=0)

class AccountRequest(models.Model):
    name = models.CharField(max_length=150)
    email_address = models.EmailField()
    info = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(default=uuid.uuid4,editable=False)
    pending_verification = models.BooleanField(default=False)
    pending_date = models.DateTimeField(null=True,blank=True)
    later = models.BooleanField(default=False)
    complete = models.DateTimeField(null=True,blank=True)

    def text_date(self):
        return self.date.strftime('%b %-d, %Y @ %-I:%M%p')

    def has_account(self):

        try:
            account = CustomUser.objects.get(email=self.email_address)
        except:
            account = None

        return account

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return self.name

class AccountRequestNote(models.Model):
    accountrequest = models.ForeignKey(AccountRequest,on_delete=models.CASCADE)

app/templates/app/duespayment_list.html
{% extends "appbase.html" %}

{% block content %}
<div class="container mb-3" style="max-width:568px;">

  <div class="row py-3 d-flex align-items-center px-2">
    <div class="col-8">
      <h3 class="fw-bold mb-0">Dues Payments</h3>
    </div>

    {% if not title %}
    <div class="col-4">
      <div class="d-grid">
        <a class="btn btn-outline-secondary"
          href="{% url 'app:duespayment-list' %}">
          <i class="fas fa-sync-alt"></i>
          Reset
        </a>
      </div>
    </div>
    {% endif %}<!-- if not title. aka no search was done -->

  </div>

  <div class="row">

    <div class="col-12">
      <div class="mb-3">
      <form  method="post">{% csrf_token %}
        <input class="form-control" type="text" name="q"
          placeholder="Enter Search Terms">
      </form>
      </div>
    </div>

    {% if title %}
    <div class="col-12">
      <span class="fw-bold">{{ title }}</span>
    </div>
    {% endif %}

    <div class="col-12">
      <ul class="list-group">
        {% for dues in payment_list %}
          <li class="list-group-item">

            {{ dues.name }}
            <span class="d-block d-md-none"></span>
            ({{ dues.email }})

            <br>

            <span class="text-sm text-muted">
              {{ dues.text_date }}
            </span>

          </li>
        {% endfor %}
      </ul>
    </div>

  </div>

</div>
{% endblock %}

app/templates/app/entry_list.html
{% extends "appbase.html" %}

{% block content %}
<div class="container" style="max-width:568px;">
  <div class="row">

    <div class="col-12">

      <a href="{% url 'app:profile-detail' profile.id %}">
        &laquo Back to {{ profile }}
      </a>

      <h1 class="h3 mt-2">
         {{ title }}
      </h1>

      <hr>

    </div>

    <div class="col-12">
      <form method="post">{% csrf_token %}
        <div class="mb-3">
          <label for="">Add New {{ singular }}</label>
          <input class="form-control" type="text" name="text">
        </div>
        <div class="bg-light border p-2">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" name="home">
            <label class="form-check-label" for="flexCheckDefault">
              Home Highlight?
            </label>
          </div>
        </div>
        <div class="my-3">
          <div class="d-grid">
            <button class="btn btn-secondary" type="submit">
              Add Entry
            </button>
          </div>
        </div>
      </form>
    </div>

    <div class="col-12">
      <ul class="list-group">
        {% for entry in entry_list %}
          <li class="list-group-item">
            <div class="row d-flex align-items-center">
              <div class="col-10">

                {% if entry.show_on_home %}
                  <i class="fas fa-home"></i>
                {% endif %}

                {{ entry.text }}
              </div>
              <div class="col-2 text-center">
                <a class="text-danger" href="{% url 'app:entry-delete' entry.id %}">
                  <i class="fas fa-trash"></i>
                </a>
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>


  </div>
</div>
{% endblock %}

app/templates/app/event_list.html
{% extends "appbase.html" %}

{% block content %}
<div class="container" style="max-width:568px;">
  <div class="row">
    <div class="col-12">
      <ul class="list-group">
        {% for event in event_set %}
          <li class="list-group-item">
            <a href="{% url 'app:event-detail' event.id %}">
              {{ event }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

app/templates/app/profile_dates.html
{% extends "appbase.html" %}

{% block content %}
<div class="container" style="max-width:568px;">
  <div class="row">

    <!--- updated notification column -->
    {% if update_notice %}
    <div class="col-12">
      <div class="alert alert-warning text-center">
        Profile Updated!
      </div>
    </div>
    {% endif %}

    <div class="col-12">
      <a href="{% url 'app:profile-detail' profile.id %}">
        &laquo Back to Profile
      </a>
      <h1>{{ profile }}</h1>
    </div>

    <div class="col-12">

      <ul class="list-group mt-3">

        {% for date in teamdate_set %}
          <li class="list-group-item">
            <div class="row">
              <div class="col-9">
                Team: {{ date.start_year }} - {{ date.end_year }}
              </div>
              <div class="col-3 text-center">
                <a class="text-danger"
                  href="{% url 'app:teamdate-delete' date.id %}">
                  <i class="fas fa-trash"></i>
                </a>
              </div>
            </div>
          </li>
        {% endfor %}

        {% for date in armydate_set %}
          <li class="list-group-item">
            <div class="row">
              <div class="col-9">
                Army: {{ date.start_year }} - {{ date.end_year }}
              </div>
              <div class="col-3 text-center">
                <a class="text-danger"
                  href="{% url 'app:armydate-delete' date.id %}">
                  <i class="fas fa-trash"></i>
                </a>
              </div>
            </div>
          </li>
        {% endfor %}

      </ul>

    </div>

    <div class="col-12">
      <form method="post">{% csrf_token %}

        <div class="row">
          <div class="col-6 mt-3">
            <div class="mb-3">
              <label for="">Team Start Year</label>
              <input class="form-control" type="text"
                name="team_start_year" placeholder="YYYY">
            </div>
          </div>

          <div class="col-6 mt-3">
            <div class="mb-3">
              <label for="">Team End Year</label>
              <input class="form-control" type="text"
                name="team_end_year" placeholder="YYYY">
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-6 mt-3">
            <div class="mb-3">
              <label for="">Army Start Year</label>
              <input class="form-control" type="text"
                name="army_start_year" placeholder="YYYY">
            </div>
          </div>

          <div class="col-6 mt-3">
            <div class="mb-3">
              <label for="">Army End Year</label>
              <input class="form-control" type="text"
                name="army_end_year" placeholder="YYYY">
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-12">
            <div class="alert alert-info text-sm">
              You do not need to add Deceased Year if you have the Deceased Date.
              Deceased Date (the full date) is preferred.
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-6 mt-3">
            <div class="mb-3">
              <label for="">Deceased Date</label>
              <input class="form-control" type="text" name="deceased_date"
                value="{{ deceased_date }}" placeholder="YYYY-MM-DD">
            </div>
          </div>

          <div class="col-6 mt-3">
            <div class="mb-3">
              <label for="">Deceased Year</label>
              <input class="form-control" type="text" name="deceased_year"
                value="{{ deceased_year }}" placeholder="YYYY">
            </div>
          </div>

        </div>

        <div class="row">
          <div class="col-12">
            <div class="d-grid mb-3">
              <button class="btn btn-primary" type="submit">
                Update the Dates
              </button>
            </div>
          </div>
        </div>

      </form>
    </div>

  </div>

</div>
{% endblock %}

app/templates/app/profile_priority_list.html
{% extends "app_base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid bg-light non-mobile-border">

  <div class="row">

    <div class="d-none d-sm-block col-sm-4 col-lg-3 app-nav">

    </div>

    <div class="col-12 app-content">
      <ul class="list-group">
        {% for profile in profile_list %}
          <li class="list-group-item">

          <div class="row d-flex align-items-center">

            <div class="col-8">
              {{ profile }}
            </div>

            <div class="col-4 d-flex justify-content-around">
              <a href="{% url 'app:profile-go' profile.id %}" target="_blank">
                <i class="fas fa-edit text-primary text-xl"></i>
              </a>
              <a href="#">
                <i class="fas fa-check text-black-50 text-xl"></i>
              </a>
            </div>
          </div>

          </li>
        {% endfor %}
      </ul>
    </div>

  </div><!--- end row --->

</div><!--- end container --->
{% endblock %}

app/templates/app/profilestory_delete.html
{% extends "appbase.html" %}

{% block content %}
<div class="container" style="max-width:568px;">

  <div class="row">

    <div class="col-12">

      <a href="{% url 'app:profile-detail' profile.id %}">
        &laquo Profile Home
      </a>

      <a class="ms-3" href="">
        &laquo My Stories
      </a>

      <hr>

    </div>

  </div>


  <div class="row">
    <div class="col-12">
      <h3 class="fw-bold">Are You Sure?</h3>

      <p>
        Are you sure you want to delete this Story?
        <span class="d-md-block"></span>
        You cannot undo this.
      </p>

      <div class="d-grid">
        <a class="btn btn-danger"
          href="{% url 'app:profilestory-delete' profile.id story.id %}?confirm=true">
          Delete Story
        </a>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-12">

      <hr>

      <h3 class="fw-bold mb-0">
        {{ story.title }}
      </h3>

      <p class="mt-0 text-muted text-sm">
        {{ story.date_text }}
      </p>

      <p>
        {{ story.text|safe }}
      </p>

    </div>
  </div>

</div>
{% endblock %}

app/templates/app/profilestory_list.html
{% extends "appbase.html" %}

{% block content %}
<div class="container" style="max-width:568px;">

  <div class="row">

    <div class="col-12">

      <a href="{% url 'app:profile-detail' profile.id %}">
        &laquo Back to Profile Home
      </a>

      <h1 class="fw-bold h2">
        Story List
      </h1>

      <a href="{% url 'app:profilestory-new' profile.id %}">
        <i class="fas fa-plus"></i>
        Add New Story
      </a>

    </div>

  </div>

  <div class="row">

    {% if story_set %}
    <div class="col-12">
      <ul class="list-group my-3">
        {% for story in story_set %}
          <li class="list-group-item">
            <div class="row d-flex align-items-center">
              <div class="col-10">
                <a href="{% url 'app:profilestory-detail' profile.id story.id %}">
                  {{ story.the_title }} &raquo;
                </a>
                <br>
                <span class="text-muted" style="font-size:1rem;">
                  {{ story.date_text }}
                </span>
              </div>
              <div class="col-2 text-center">
                <a href="{% url 'app:profilestory-edit' profile.id story.id %}">
                  <i class="fas fa-edit"></i>
                </a>
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>

    {% else %}<!-- if not comment_set -->

    <div class="col-12">
      <p class="mb-0">
        You have no stories:
      </p>
      <a href="">
        + Add One Now
      </a>
    </div>

    {% endif %}<!-- end if no comment set -->

  </div>

</div>
{% endblock %}

app/templates/app/profilestory_new.html
{% extends "appbase.html" %}

{% block content %}
<div class="container" style="max-width:668px;">

  <div class="row">

    <div class="col-12 mb-3">

      <a href="{% url 'app:profile-detail' profile.id %}">
        &laquo Profile
      </a>

      <a class="ms-3" href="">
        &laquo Story List
      </a>

    </div>

  </div>


  <div class="row">

    <form  method="post">{% csrf_token %}

      <div class="col-12 mb-3">
        <label for="title">
          Story Title
          <span class="text-sm text-muted">(optional)</span>
        </label>
        <input class="form-control mt-1" type="text" name="title"
          placeholder="Optional Title">
      </div>

      <div class="col-12">
        <input id="x" type="hidden" name="text" value="{{ draft_entry.text }}">
        <trix-editor class="trix-content" input="x"></trix-editor>
      </div>

      <div class="col-12">
        <div class="d-grid my-3">
          <button class="btn btn-primary" type="submit">
            Add New Story
          </button>
        </div>
      </div>

    </form>

  </div>

</div>
{% endblock %}

app/templates/app/search.html
{% extends "appbase.html" %}

{% block content %}
<div class="container" style="max-width:568px;">

  <div class="row">
    <div class="col-12">
      <span class="fw-bold">Search Terms:</span> {{ query }}
      <hr>
    </div>
  </div>


    {% if profile_set %}
    <div class="row">
      <div class="col-12">
        <ul class="list-group">
          {% for profile in profile_set %}
          <li class="list-group-item">
            <a href="{% url 'app:profile-detail' profile.id %}">
              {{ profile }}
            </a><br>
            <span class="text-sm text-muted">
              {{ profile.date_text }}
            </span>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    {% endif %}

  </div>
</div>
{% endblock %}

app/templates/app/subevent_detail.html
{% extends "appbase.html" %}

{% block content %}
<div class="container" style="max-width:568px;">

  <div class="row">
    <div class="col-12 py-3">
      <a href="{% url 'app:event-detail' event.id %}">
        &laquo;{{ event }}
      </a>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <h1 class="h2">
        {{ subevent }} ({{ num_attendees }})
      </h1>
    </div>
    <div class="col-12">
      <ul class="list-group">
        {% for reg in reg_list %}
          <li class="list-group-item">
            {{ reg.last_name }}, {{ reg.first_name }}
            ({{ reg.quantity }})
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>

</div>
{% endblock %}

app/templates/app/user_list.html
{% extends "appbase.html" %}

{% block content %}
<div class="container" style="max-width:568px;">

  <div class="row">
    <div class="col-12">
      <form method="post">{% csrf_token %}
        <div class="mb-3">
          <label>Search Users</label>
          <input class="form-control" type="text" name="q" placeholder="Search Users">
        </div>
      </form>
    </div>
  </div>


  <div class="row">

    <div class="col-12">
      <ul class="list-group">
        {% for user in user_set %}
          <li class="list-group-item">
            <a href="{% url 'app:customuser-detail' user.id %}">
              {{ user.name }}
            </a>
            <br>
            <span class="text-sm text-muted">
              {{ user.email }}<br>
              Set up: {{ user.text_date }}
            </span>
          </li>
        {% endfor %}
      </ul>
    </div>

  </div>
</div>
{% endblock %}